#
# MMOExtended by Sek
#
# Requires MMOLib.
#
# Supports MMOItems, MMOCore, StackableItems
#
#
# Defense Formula
# Defense applies at the lowest event level
#
# <def> = DefenseListener Level
# Damage = Damage - (Damage * Defense-Formula)
#
defense-formula: <def>/(<def>+100)

